services:
  backend:
    image: backend:backend  # my custom build image from docker build.
    privileged: true
    user: root
    ports:
      - 3000:3000
    env_file:
      - .env
    container_name: backend-backend